/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import entity.*;
import java.awt.Color;
/**
 *
 * @author Yudho
 */
public class PanelKendaraan extends javax.swing.JPanel {
    private int index;
    private Kendaraan K;
    /**
     * Creates new form PanelKendaraan
     */
    public PanelKendaraan(Kendaraan K,int index) {
        initComponents();
        this.K = K;
        this.index = index;
        lblIDKendaraan.setText(String.format("%03d", K.getId()));
        switch(K.getJenis()){
            case 1:
                lblNoPlat.setText(((Mobil)K).getNoplat().toUpperCase());
                lblJenis.setText("MOBIL");
                pnlBand.setBackground(Color.ORANGE);
                break;
            case 2:
                lblNoPlat.setText(((Motor)K).getNoplat().toUpperCase());
                lblJenis.setText("MOTOR");
                pnlBand.setBackground(Color.GREEN);
                break;
            default:
                lblNoPlat.setText(((Sepeda)K).getNoktp().toUpperCase());
                lblJenis.setText("SEPEDA");
                pnlBand.setBackground(Color.cyan);
                break;
        }
        
        lblMasuk.setText(K.getWaktu_Masuk().toString());
        if(K.getWaktu_keluar() != null)
        {
            lblKeluar.setText(K.getWaktu_keluar().toString());
            btnCheckout.setEnabled(false);
        }
        else
            lblKeluar.setText("");
        if(index % 2 == 0){
            setBackground(new Color(204,255,204));
        }
        else if(index % 3 == 0){
            setBackground(new Color(204,204,255));
        }
        else
            setBackground(new Color(255,255,204));
    }
    public Kendaraan GetKendaraan(){
        return K;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBand = new javax.swing.JPanel();
        lblNoPlat = new javax.swing.JLabel();
        lblJenis = new javax.swing.JLabel();
        lblMasuk = new javax.swing.JLabel();
        lblKeluar = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        lblIDKendaraan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setToolTipText("Klik Untuk Masuk Ke Detail");
        setMaximumSize(new java.awt.Dimension(32767, 40));
        setMinimumSize(new java.awt.Dimension(717, 40));
        setPreferredSize(new java.awt.Dimension(717, 40));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        pnlBand.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout pnlBandLayout = new javax.swing.GroupLayout(pnlBand);
        pnlBand.setLayout(pnlBandLayout);
        pnlBandLayout.setHorizontalGroup(
            pnlBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        pnlBandLayout.setVerticalGroup(
            pnlBandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblNoPlat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoPlat.setForeground(new java.awt.Color(51, 51, 0));
        lblNoPlat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoPlat.setText("AB 9067 RY");
        lblNoPlat.setToolTipText("No Indetifikasi Kendaraan");

        lblJenis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJenis.setForeground(new java.awt.Color(51, 0, 0));
        lblJenis.setText("SEPEDA");
        lblJenis.setToolTipText("Jenis Kendaraan");

        lblMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMasuk.setText("04/09/2017");
        lblMasuk.setToolTipText("Waktu Masuk Kendaraan");

        lblKeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKeluar.setForeground(new java.awt.Color(255, 51, 51));
        lblKeluar.setText("05/09/2017");
        lblKeluar.setToolTipText("Waktu Keluar Kendaraan");

        btnCheckout.setBackground(new java.awt.Color(0, 0, 204));
        btnCheckout.setForeground(new java.awt.Color(255, 102, 255));
        btnCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/btn_checkout.png"))); // NOI18N
        btnCheckout.setToolTipText("Jika Kendaraan Ingin Keluar");
        btnCheckout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        btnCheckout.setBorderPainted(false);
        btnCheckout.setContentAreaFilled(false);
        btnCheckout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCheckout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/btn_checkout_rollover.png"))); // NOI18N
        btnCheckout.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/btn_checkout_rollover.png"))); // NOI18N
        btnCheckout.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/btn_checkout_rollover.png"))); // NOI18N
        btnCheckout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        lblIDKendaraan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDKendaraan.setForeground(new java.awt.Color(102, 102, 102));
        lblIDKendaraan.setText("001");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIDKendaraan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJenis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(lblMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeluar)
                .addGap(57, 57, 57)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIDKendaraan)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNoPlat)
                            .addComponent(lblJenis)
                            .addComponent(lblMasuk)
                            .addComponent(lblKeluar))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCheckout)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new Color(0,0,51));
        lblMasuk.setForeground(new Color(255,255,255));
        lblJenis.setForeground(new Color(204,0,51));
        lblNoPlat.setForeground(new Color(153,153,0));
        lblIDKendaraan.setForeground(new Color(204,204,255));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if(index % 2 == 0){
            setBackground(new Color(204,255,204));
        }
        else if(index % 3 == 0){
            setBackground(new Color(204,204,255));
        }
        else
            setBackground(new Color(255,255,204));
        
        lblMasuk.setForeground(new Color(0,0,0));
        lblJenis.setForeground(new Color(51,0,51));
        lblNoPlat.setForeground(new Color(51,51,0));
        lblIDKendaraan.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JLabel lblIDKendaraan;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblKeluar;
    private javax.swing.JLabel lblMasuk;
    private javax.swing.JLabel lblNoPlat;
    private javax.swing.JPanel pnlBand;
    // End of variables declaration//GEN-END:variables
}
